CREATE TABLE IF NOT EXISTS `reserve_layout_company_staff`  (
    `id` varchar(37)  NOT NULL COMMENT '主键ID(单位代码-身份证号码)',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    `kqdm` varchar(21)  NULL DEFAULT NULL COMMENT '库区代码',
    `dwmc` varchar(256)  NOT NULL COMMENT '单位名称',
    `lsbm` varchar(256)  NOT NULL COMMENT '隶属部门',
    `xzqhdm` varchar(6)  NOT NULL COMMENT '行政区划代码',
    `xm` varchar(32)  NOT NULL COMMENT '姓名',
    `xb` char(1)  NOT NULL COMMENT '性别',
    `sfzhm` char(18)  NOT NULL COMMENT '身份证号码',
    `rzrq` date NOT NULL COMMENT '入职日期',
    `gwxz` char(2)  NOT NULL COMMENT '岗位性质',
    `zgzt` char(2)  NOT NULL COMMENT '在岗状态',
    `lzrq` date NULL DEFAULT NULL COMMENT '离职日期',
    `zjdh` varchar(16)  NULL DEFAULT NULL COMMENT '座机电话',
    `yddh` varchar(16)  NULL DEFAULT NULL COMMENT '移动电话',
    `dzyx` varchar(32)  NULL DEFAULT NULL COMMENT '电子邮箱',
    `mz` char(2)  NOT NULL COMMENT '民族',
    `zzmm` char(2)  NOT NULL COMMENT '政治面貌',
    `rylb` char(4)  NOT NULL COMMENT '人员类别',
    `zy` varchar(128)  NULL DEFAULT NULL COMMENT '专业',
    `qdzgzchzyzgsj` date NULL DEFAULT NULL COMMENT '取得最高职称或职业资格时间',
    `xl` char(1)  NOT NULL COMMENT '学历',
    `zw` varchar(16)  NULL DEFAULT NULL COMMENT '职务',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `zyzgzsbh` varchar(255)  NULL DEFAULT NULL COMMENT '职业资格证书编号',
    `fzjg` varchar(255)  NULL DEFAULT NULL COMMENT '发证机关',
    `status` char(1)  NOT NULL DEFAULT '0' COMMENT '状态 0：保存，1：提交，2：审核',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_sfzhm`(`dwdm`, `sfzhm`) USING BTREE COMMENT '单位代码/身份证号码组合唯一索引',
    INDEX `idx_dwmc`(`dwmc`) USING BTREE COMMENT '单位名称普通索引',
    INDEX `idx_xm`(`xm`) USING BTREE COMMENT '姓名普通索引',
    INDEX `idx_sfzhm`(`sfzhm`) USING BTREE COMMENT '身份证号码普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局地理信息-企业人员信息表' ROW_FORMAT = Dynamic;


CREATE TABLE IF NOT EXISTS `reserve_layout_attachment`  (
    `id` varchar(30)  NOT NULL COMMENT '主键ID',
    `data_id` varchar(128)  NOT NULL COMMENT '数据id',
    `file_storage_id` varchar(20)  NOT NULL COMMENT '文件存储id',
    `attachment_name` varchar(128)  NOT NULL COMMENT '附件名称',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_hwdm`(`data_id`) USING BTREE COMMENT '数据代码唯一索引',
    INDEX `idx_hwmc`(`file_storage_id`) USING BTREE COMMENT '文件id普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局地理信息-附件文件' ROW_FORMAT = Dynamic;


CREATE TABLE IF NOT EXISTS `reserve_layout_cargo`  (
    `id` varchar(30)  NOT NULL COMMENT '主键ID',
    `hwdm` varchar(30)  NOT NULL COMMENT '货位代码',
    `hwmc` varchar(256)  NOT NULL COMMENT '货位名称',
    `ajdm` varchar(28)  NOT NULL COMMENT '廒间代码',
    `hwqyrq` date NOT NULL COMMENT '货位启用日期',
    `hwrl` decimal(20, 6) NULL DEFAULT NULL COMMENT '货位容量',
    `bgdw` varchar(128)  NULL DEFAULT NULL COMMENT '保管单位',
    `bgy` varchar(128)  NULL DEFAULT NULL COMMENT '保管员',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `status` char(1)  NOT NULL DEFAULT '' COMMENT '状态 0：保存，1：提交，2：审核',
    `kqdm` varchar(21)  NOT NULL COMMENT '库区代码',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    `cfdm` varchar(18)  NOT NULL COMMENT '仓房代码',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_hwdm`(`hwdm`) USING BTREE COMMENT '货位代码唯一索引',
    INDEX `idx_hwmc`(`hwmc`) USING BTREE COMMENT '货位名称普通索引',
    INDEX `idx_ajdm`(`ajdm`) USING BTREE COMMENT '廒间代码普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局地理信息-货位信息表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `reserve_layout_granary`  (
    `id` varchar(28)  NOT NULL COMMENT '主键ID(廒间代码)',
    `ajdm` varchar(28)  NOT NULL COMMENT '廒间代码',
    `ajmc` varchar(256)  NOT NULL COMMENT '廒间名称',
    `cfhygdm` varchar(25)  NOT NULL COMMENT '仓房(或油罐)编码',
    `ajcd` decimal(8, 4) NULL DEFAULT NULL COMMENT '廒间长度',
    `ajkd` decimal(8, 4) NULL DEFAULT NULL COMMENT '廒间宽度',
    `ajgd` decimal(8, 4) NULL DEFAULT NULL COMMENT '廒间高度',
    `ajsjcr` decimal(20, 3) NOT NULL COMMENT '廒间设计仓容',
    `ajqyrq` date NULL DEFAULT NULL COMMENT '廒间启用日期',
    `ajzt` char(1)  NOT NULL COMMENT '廒间状态',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `status` char(1)  NOT NULL DEFAULT '' COMMENT '状态 0：保存，1：提交，2：审核',
    `kqdm` varchar(21)  NOT NULL COMMENT '库区代码',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_ajdm`(`ajdm`) USING BTREE COMMENT '廒间代码唯一索引',
    INDEX `idx_ajmc`(`ajmc`) USING BTREE COMMENT '廒间名称普通索引',
    KEY `idx_cfbh` (`cfhygdm`) USING BTREE COMMENT '仓房(或油罐)编码普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
) ENGINE = InnoDB  COMMENT = '储备布局地理信息-廒间信息表' ROW_FORMAT = Dynamic;


CREATE TABLE IF NOT EXISTS `reserve_layout_stock_house`  (
    `id` varchar(21)  NOT NULL,
    `kqdm` varchar(21)  NOT NULL COMMENT '库区代码',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    `kqmc` varchar(256)  NOT NULL COMMENT '库区名称',
    `kqdz` varchar(512)  NOT NULL COMMENT '库区地址',
    `xzqhdm` varchar(6)  NOT NULL COMMENT '行政区划代码',
    `kqcq` varchar(1)  NOT NULL COMMENT '库区产权',
    `yxcr` decimal(20, 6) NOT NULL COMMENT '有效仓容',
    `yxgr` decimal(20, 6) NOT NULL COMMENT '有效罐容',
    `zdmj` decimal(20, 6) NOT NULL COMMENT '占地面积',
    `cfs` int(0) NOT NULL COMMENT '仓房数',
    `ygs` int(0) NOT NULL COMMENT '油罐数',
    `jd` decimal(20, 6) NOT NULL COMMENT '库区经度',
    `wd` decimal(20, 6) NOT NULL COMMENT '库区纬度',
    `status` char(1)  NOT NULL DEFAULT '0' COMMENT '状态 0：保存，1：提交，2：审核',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `jscr` decimal(20, 0) NULL DEFAULT NULL COMMENT '建设仓容(吨)',
    `jsgr` decimal(20, 6) NULL DEFAULT NULL COMMENT '建设罐容(吨)',
    `kqlxr` varchar(256)  NULL DEFAULT NULL COMMENT '库区联系人',
    `kqlxrsjh` varchar(32)  NULL DEFAULT NULL COMMENT '库区联系人手机号',
    `dwmc` varchar(256)  NULL DEFAULT NULL COMMENT '单位名称',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_kqdm`(`kqdm`) USING BTREE COMMENT '库区代码唯一索引',
    INDEX `idx_kqmc`(`kqmc`) USING BTREE COMMENT '库区名称普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局地理信息-粮库信息备案表' ROW_FORMAT = Dynamic;


CREATE TABLE IF NOT EXISTS `reserve_layout_tank`  (
    `id` varchar(25)  NOT NULL COMMENT '主键ID(油罐代码)',
    `ygdm` varchar(25)  NOT NULL COMMENT '油罐代码',
    `ygmc` varchar(256)  NOT NULL COMMENT '油罐名称',
    `kqdm` varchar(21)  NOT NULL COMMENT '库区代码',
    `gr` decimal(20, 6) NOT NULL COMMENT '罐容',
    `jzsj` date NOT NULL COMMENT '建造时间',
    `ygjfssssfwh` char(1)  NOT NULL COMMENT '油罐及附属设施是否完好',
    `ywjrzz` char(1)  NOT NULL COMMENT '有无加热装置',
    `yglx` char(1)  NOT NULL COMMENT '油罐类型',
    `gnzj` decimal(20, 6) NULL DEFAULT NULL COMMENT '罐内直径',
    `gngd` decimal(20, 6) NULL DEFAULT NULL COMMENT '罐内高度',
    `jdfs` char(1)  NULL DEFAULT NULL COMMENT '检定方式',
    `hjfs` char(1)  NULL DEFAULT NULL COMMENT '焊接方式',
    `ygzt` char(1)  NOT NULL COMMENT '油罐状态',
    `sjdw` varchar(256)  NULL DEFAULT NULL COMMENT '设计单位',
    `jsdw` varchar(256)  NULL DEFAULT NULL COMMENT '建设单位',
    `jldw` varchar(256)  NULL DEFAULT NULL COMMENT '监理单位',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `status` char(1)  NOT NULL DEFAULT '' COMMENT '状态 0：保存，1：提交，2：审核',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_ygdm`(`ygdm`) USING BTREE COMMENT '油罐代码唯一索引',
    INDEX `idx_ygmc`(`ygmc`) USING BTREE COMMENT '油罐名称普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局地理信息-油罐信息表' ROW_FORMAT = Dynamic;


CREATE TABLE IF NOT EXISTS `reserve_layout_warehouse`  (
    `id` varchar(25)  NOT NULL COMMENT '主键ID',
    `cfdm` varchar(25)  NOT NULL COMMENT '仓房代码',
    `cfmc` varchar(256)  NOT NULL COMMENT '仓房名称',
    `kqdm` varchar(21)  NOT NULL COMMENT '库区代码',
    `cflxdm` char(8)  NOT NULL COMMENT '仓房类型代码',
    `jfsyrq` date NULL DEFAULT NULL COMMENT '交付使用日期',
    `jsdw` varchar(256)  NULL DEFAULT NULL COMMENT '建设单位',
    `sjsynx` varchar(32)  NULL DEFAULT NULL COMMENT '设计使用年限',
    `sjdw` varchar(256)  NULL DEFAULT NULL COMMENT '设计单位',
    `jldw` varchar(256)  NULL DEFAULT NULL COMMENT '监理单位',
    `qtjg` char(2)  NOT NULL COMMENT '墙体结构',
    `fdjg` char(2)  NOT NULL COMMENT '房顶结构',
    `fjjg` char(2)  NOT NULL COMMENT '房架结构',
    `dmjg` char(2)  NOT NULL COMMENT '地面结构',
    `sjcr` decimal(20, 6) NOT NULL COMMENT '设计仓容',
    `cwc` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓外长',
    `cwk` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓外宽',
    `cwyg` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓外檐高',
    `cwdg` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓外顶高',
    `tcwj` decimal(20, 6) NOT NULL COMMENT '筒仓外径',
    `cnc` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓内长',
    `cnk` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓内宽',
    `cnyg` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓内檐高',
    `cnzlxg` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓内装粮线高',
    `tcnj` decimal(20, 6) NOT NULL COMMENT '筒仓内径',
    `cntj` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓内体积',
    `cmsl` int(0) NULL DEFAULT NULL COMMENT '仓门数量',
    `cmwz` varchar(256)  NULL DEFAULT NULL COMMENT '仓门位置',
    `cmgd` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓门高度',
    `cmkd` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓门宽度',
    `dlmxs` char(2)  NULL DEFAULT NULL COMMENT '挡粮门型式',
    `cfsfwh` char(1)  NOT NULL COMMENT '仓房是否完好',
    `clgx` char(1)  NOT NULL COMMENT '储粮功效',
    `nfgrbw` char(1)  NOT NULL COMMENT '能否隔热保温',
    `grbwcs` varchar(512)  NULL DEFAULT NULL COMMENT '隔热保温措施',
    `grxn` char(1)  NOT NULL COMMENT '隔热性能',
    `jgcl` char(1)  NOT NULL COMMENT '结构材料',
    `qmx` char(1)  NOT NULL COMMENT '气密性',
    `sfyjxxxhgz` char(1)  NOT NULL COMMENT '是否已进行信息化改造',
    `lqjs` char(1)  NOT NULL COMMENT '粮情技术',
    `nfszcc` char(1)  NOT NULL COMMENT '能否散装储存',
    `ywfsfqfczz` char(1)  NOT NULL COMMENT '有无防鼠防雀防虫装置及设施',
    `ywfhfbfdss` char(1)  NOT NULL COMMENT '有无防火防爆防盗设施',
    `ywjxtfss` char(1)  NOT NULL COMMENT '有无机械通风设施',
    `tfxtxs` char(1)  NULL DEFAULT NULL COMMENT '通风系统型式',
    `tfjs` char(1)  NOT NULL COMMENT '通风技术',
    `nfhlxzsc` char(1)  NOT NULL COMMENT '能否环流熏蒸杀虫',
    `scjs` char(1)  NULL DEFAULT NULL COMMENT '杀虫技术',
    `nffddyqtcl` char(1)  NOT NULL COMMENT '能否富氮低氧气调储粮',
    `kwjs` char(1)  NULL DEFAULT NULL COMMENT '控温技术',
    `hcjcfs` char(2)  NOT NULL COMMENT '害虫检测方式',
    `cfzt` char(1)  NOT NULL COMMENT '仓房状态',
    `bgr` varchar(128)  NOT NULL COMMENT '保管员',
    `jd` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓房经度',
    `wd` decimal(20, 6) NULL DEFAULT NULL COMMENT '仓房纬度',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `status` char(1)  NOT NULL DEFAULT '' COMMENT '状态 0：保存，1：提交，2：审核',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    PRIMARY KEY (`id`, `update_time`) USING BTREE,
    UNIQUE INDEX `unx_cfdm`(`cfdm`) USING BTREE COMMENT '仓房代码唯一索引',
    INDEX `idx_cfmc`(`cfmc`) USING BTREE COMMENT '仓房名称普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局地理信息-仓房信息表' ROW_FORMAT = Dynamic;

CREATE TABLE IF NOT EXISTS `reserve_layout_testing_institutes`  (
  `id` int(0) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `zjjgmc` varchar(128)  NOT NULL COMMENT '质检机构名称',
  `dwlxr` varchar(64)  NOT NULL COMMENT '单位联系人',
  `lxdh` varchar(20)  NOT NULL COMMENT '联系电话',
  `sfqy` varchar(1)  NOT NULL DEFAULT '0' COMMENT '是否启用，0：启用，1：未启用',
  `dwdz` varchar(512)  NOT NULL COMMENT '单位地址',
  `bz` varchar(1024)  NULL DEFAULT NULL COMMENT '备注',
  `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
  `update_time` datetime(0) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB  COMMENT = '储备布局地理信息-质检机构' ROW_FORMAT = Dynamic;