CREATE TABLE IF NOT EXISTS `apparitor_reserve_plan`  (
  `id` varchar(66)  NOT NULL COMMENT '主键ID(计划单号)',
  `jhdh` varchar(66)  NOT NULL COMMENT '计划单号',
  `jhwh` varchar(128)  NULL DEFAULT NULL COMMENT '计划文号',
  `jhmc` varchar(256)  NULL DEFAULT NULL COMMENT '计划名称',
  `jhnd` char(4)  NULL DEFAULT NULL COMMENT '计划年度',
  `jhzddw` varchar(128)  NULL DEFAULT NULL COMMENT '制定计划单位',
  `jhxdsj` datetime(0) NULL DEFAULT NULL COMMENT '计划下达时间',
  `lspzdm` varchar(7)  NULL DEFAULT NULL COMMENT '粮食品种代码',
  `lsdjdm` varchar(2)  NULL DEFAULT NULL COMMENT '粮食等级代码',
  `lsxzdm` varchar(3)  NULL DEFAULT NULL COMMENT '粮食性质代码',
  `sl` decimal(20, 3) NULL DEFAULT NULL COMMENT '数量（吨）',
  `czbz` char(1)  NOT NULL DEFAULT 'i' COMMENT '操作标志（i：新增(默认)，u：更新，d：删除）',
  `zhgxsj` datetime(0) NOT NULL COMMENT '最后更新时间',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64)  NULL DEFAULT NULL COMMENT '创建人',
  `update_time` datetime(0) NOT NULL COMMENT '修改时间',
  `update_by` varchar(64)  NULL DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18)  NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21)  NOT NULL DEFAULT '-1' COMMENT '库区ID',
  PRIMARY KEY (`id`, `update_time`) USING BTREE,
  UNIQUE INDEX `unx_jhdh`(`jhdh`) USING BTREE COMMENT '计划单号唯一索引',
  INDEX `idx_jhmc`(`jhmc`) USING BTREE COMMENT '计划名称普通索引',
  INDEX `idx_jhwh`(`jhwh`) USING BTREE COMMENT '计划年度普通索引',
  INDEX `idx_jhnd`(`jhnd`) USING BTREE COMMENT '计划文号普通索引',
  INDEX `idx_jhxdsj`(`jhxdsj`) USING BTREE COMMENT '计划下达时间普通索引',
  INDEX `idx_lspzdm`(`lspzdm`) USING BTREE COMMENT '粮食品种代码普通索引',
  INDEX `idx_lsdjdm`(`lsdjdm`) USING BTREE COMMENT '粮食等级代码普通索引',
  INDEX `idx_lsxzdm`(`lsxzdm`) USING BTREE COMMENT '粮食性质代码普通索引',
  INDEX `idx_region_id`(`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  INDEX `idx_region_ids`(`country_id`, `province_id`, `city_id`, `area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  INDEX `idx_enterprise`(`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  INDEX `idx_stock_house`(`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE = InnoDB COMMENT = '行政管理-储备计划表';