create table if not exists  monitoring_statistics(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `good_company_id` varchar(40) not null comment '好粮油企业ID',
    `data_date` date not null comment '数据日期',
    `operate_area` varchar(20) comment '经营区域',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-粮油流通统计';

create table if not exists monitoring_statistics_storage_facilities(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `has_assays_room` tinyint(1) DEFAULT NULL COMMENT '有专用检测化验室',
    `has_assays_rule_check_ability` tinyint(1) DEFAULT 0 COMMENT '检化验相关情况：具有粮油常规检验能力',
    `has_grain_oil_quality_check_ability` tinyint(1) default  0 comment '具有粮油品质检验能力',
    `has_danger_source`tinyint(1) DEFAULT 0 comment '周边有无危险源',
    `has_pollute_source`tinyint(1) DEFAULT 0 comment '周边有无污染源',
    `has_ground_quality_check_ability` tinyint(1) DEFAULT 0 comment '经营场地周边环境情况：经营具有粮油品质检验能力',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-仓储设施';

create table if not exists monitoring_statistics_storehouse(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `code` varchar(40) comment '库点编号',
    `name` varchar(40) comment '库点名称',
    `area` decimal(12, 6) comment '占地面积',
    `build_warehouse_cap` decimal(12, 6) comment '建设仓容（吨）',
    `actual_warehouse_cap` decimal(12, 6) comment '实际仓容（吨）',
    `build_tank_cap` decimal(12, 6) comment '建设罐容（吨）',
    `actual_tank_cap` decimal(12, 6) comment '实际罐容（吨）',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-库点信息';

create table if not exists monitoring_statistics_processing_rotation(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `code` varchar(40) comment '计划文号',
    `material_type` varchar(40) comment '物料分类',
    `plan_year` varchar(4) comment '计划年度',
    `plan_qty` decimal(12, 6) comment '计划数量',
    `material_unit` varchar(40) comment '单位，字典：kcsldw',
    `rotation_type` varchar(40) comment '轮换类型，字典：lhlx',
    `rotation_storehouse` varchar(40) comment '轮换库点',
    `in_qty` decimal(12, 6) comment '轮入数量',
    `out_qty` decimal(12, 6) comment '轮出数量',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-加工轮换';

create table if not exists monitoring_statistics_science_info(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `project_name` varchar(40) comment '科技项目名称',
    `total` decimal(12,2) comment '总资金（万元）',
    `content` varchar(200) comment '建设内容',
    `current_progress` varchar(40) comment '目前进度',
    `subsidy_amount` decimal(12,2) comment '财政补贴资金（万元）',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-粮油科技信息';

create table if not exists monitoring_statistics_income_expenses(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `in_total` decimal(12, 2) comment '收入情况（万元）',
    `out_total` decimal(12, 2) comment '支出情况（万元）',
    `month` varchar(8) comment '月份',
    `other_in_total` decimal(12, 2) comment '其它收入情况（万元）',
    `other_out_total` decimal(12, 2) comment '其它支出情况（万元）',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-粮油收支平衡数据';

create table if not exists monitoring_statistics_stock_scale(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `grain_oil_nature` varchar(40) comment '粮油性质',
    `material_type` varchar(40) comment '品种',
    `store_scale` varchar(40) comment '储备规模（吨）',
    `store_plan_no` varchar(40) comment '储备计划文号',
    `year` varchar(40) comment '年度',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-库存规模';

create table if not exists monitoring_statistics_purchase_sale(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `purchase_sale_type` varchar(20) comment '单据类型',
    `bill_code` varchar(40) comment '单据编号',
    `material_name` varchar(40) comment '物料名称',
    `qty` decimal(12, 6) comment '数量',
    `material_type` varchar(40) comment '物料品种',
    `tax_amount` decimal(12, 2) comment '含税金额',
    `base_unit` varchar(10) comment '基本单位',
    `base_qty` decimal(12, 6) comment '基本数量',
    `spec` varchar(15) comment '规格型号',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-粮油购销信息';

create table if not exists monitoring_statistics_farmer(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `administration_area` varchar(40) comment '行政区域',
    `name` varchar(40) comment '名称',
    `sex` varchar(40) comment '性别',
    `age` int comment '年龄',
    `degree` varchar(40) comment '学历',
    `phone` varchar(40) comment '电话',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-居民农户信息';

create table if not exists monitoring_statistics_process(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `type` varchar(40) comment '加工类型',
    `material` varchar(40) comment '加工物料',
    `qty` decimal(12, 6) comment '加工数量',
    `material_type` varchar(40) comment '品种',
    `price` decimal(12, 6) comment '加工单价',
    `final_qty` decimal(12,6) comment '最终加工数',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-粮油加工信息';

create table if not exists monitoring_statistics_price_check(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `material_type` varchar(40) comment '品种',
    `incoming_price` decimal(12, 2) comment '进厂价',
    `factory_price` decimal(12, 2) comment '出厂价',
    `retail_price` decimal(12, 2) comment '零售价',
    `sale_price` decimal(12, 2) comment '销售价',
    `trade_price` decimal(12, 2) comment '批发价',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-价格检测信息';

create table if not exists monitoring_statistics_check_point(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `point_id` varchar(40) not null comment '监测点ID',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-粮食市场监测点信息';

create table if not exists monitoring_statistics_infrastructure_construction(
    `id` varchar(40) NOT NULL COMMENT '主键ID',
    `statistic_id` varchar(40) not null COMMENT '粮油流通统计ID',
    `device_name` varchar(40) comment '设备名称',
    `storehouse_name` varchar(40) comment '库点名称',
    `device_type` varchar(40) comment '设备类型',
    `device_model` varchar(40) comment '设备型号',
    `unit` varchar(40) comment '计量单位',
    `device_status` varchar(40) comment '设备状态',
    `device_pic_file_id` varchar(40) comment '设备照片文件ID',
    `create_by` varchar(50) DEFAULT NULL COMMENT '添加人员',
    `create_time` datetime DEFAULT NULL COMMENT '添加时间',
    `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
    `update_time` datetime NOT NULL COMMENT '修改时间',
    `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
    `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
    `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
    `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
    `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
    `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
    `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
    PRIMARY KEY (`id`),
    KEY `idx_region_id` (`region_id`) COMMENT '行政区域ID普通索引',
    KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) COMMENT '行政地区组合索引',
    KEY `idx_update_time` (`update_time`) COMMENT '最后更新时间普通索引',
    KEY `idx_enterprise` (`enterprise_id`) COMMENT '企业ID普通索引',
    KEY `idx_stock_house` (`stock_house_id`) COMMENT '库区ID普通索引'
) comment = '流通检测-基础设施建设信息';

ALTER TABLE monitoring_statistics_price_check MODIFY COLUMN incoming_price decimal(12,2) NULL COMMENT '进厂价';
ALTER TABLE monitoring_statistics_price_check MODIFY COLUMN factory_price decimal(12,2) NULL COMMENT '出厂价';
ALTER TABLE monitoring_statistics_price_check MODIFY COLUMN retail_price decimal(12,2) NULL COMMENT '零售价';
ALTER TABLE monitoring_statistics_price_check MODIFY COLUMN sale_price decimal(12,2) NULL COMMENT '销售价';
ALTER TABLE monitoring_statistics_price_check MODIFY COLUMN trade_price decimal(12,2) NULL COMMENT '批发价';
