CREATE TABLE IF NOT EXISTS `apparitor_secure_risk_iden`  (
  `id` varchar(64)  NOT NULL COMMENT '安全生产-风险智能识别Id',
  `dwdm` varchar(64)  NULL DEFAULT '0' COMMENT '企业',
  `kqdm` varchar(50)  NULL DEFAULT NULL COMMENT '库点',
  `risk_type` varchar(2)  NULL DEFAULT NULL COMMENT '风险类型',
  `yjlx_type` varchar(2)  NULL DEFAULT NULL COMMENT '预警类型',
  `yjrq` date NULL DEFAULT NULL COMMENT '预警日期',
  `remark` longtext  NULL COMMENT '线索描述',
  `create_by` varchar(64)  NULL DEFAULT NULL COMMENT '创建者',
  `create_time` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64)  NULL DEFAULT NULL COMMENT '最后更新者',
  `update_time` datetime(0) NULL DEFAULT NULL COMMENT '最后更新时间',
  `enterprise_id` varchar(18)  NULL DEFAULT NULL COMMENT '企业ID',
  `region_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '区ID',
  `stock_house_id` varchar(21)  NULL DEFAULT '-1' COMMENT '库区ID',
  `czbz` char(1)  NOT NULL COMMENT '操作标志（i：新增(默认)，u：更新，d：删除）',
  `zhgxsj` datetime(0) NOT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_region_id`(`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  INDEX `idx_region_ids`(`country_id`, `province_id`, `city_id`, `area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  INDEX `idx_enterprise`(`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  INDEX `idx_stock_house`(`stock_house_id`) USING BTREE COMMENT '库区ID普通索引',
  INDEX `idx_dwdm`(`dwdm`) USING BTREE COMMENT '企业ID普通索引',
  INDEX `idx_kqdm`(`kqdm`) USING BTREE COMMENT '库区ID普通索引',
  INDEX `idx_risk_type`(`risk_type`) USING BTREE COMMENT '风险类型普通索引',
  INDEX `idx_yjlx_type`(`yjlx_type`) USING BTREE COMMENT '预警类型普通索引',
  INDEX `idx_yjrq`(`yjrq`) USING BTREE COMMENT '预警日期'
) ENGINE = InnoDB COMMENT = '安全生产-风险智能识别';