CREATE TABLE IF NOT EXISTS `apparitor_reserve_scale`  (
  `id` varchar(66)  NOT NULL COMMENT '主键ID(年份-承储企业-粮食品种-粮食性质)',
  `cbjh_id` varchar(66)  NOT NULL COMMENT '关联储备计划id',
  `nf` char(4)  NOT NULL COMMENT '年份',
  `xzqhdm` varchar(6)  NULL DEFAULT NULL COMMENT '行政区划代码',
  `ccqy` varchar(18)  NOT NULL COMMENT '承储企业',
  `ylpz` varchar(7)  NOT NULL COMMENT '粮食品种代码',
  `ylxz` varchar(3)  NOT NULL COMMENT '粮食性质代码',
  `ylcbgmjhsl` decimal(20, 6) NULL DEFAULT NULL COMMENT '储备规模计划数量',
  `cbgmjhwh` varchar(128)  NULL DEFAULT NULL COMMENT '储备规模计划文号',
  `remarks` varchar(256)  NULL DEFAULT NULL COMMENT '备注',
  `czbz` char(1)  NOT NULL DEFAULT 'i' COMMENT '操作标志（i：新增(默认)，u：更新，d：删除）',
  `zhgxsj` datetime(0) NOT NULL COMMENT '最后更新时间',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64)  NULL DEFAULT NULL COMMENT '创建人',
  `update_time` datetime(0) NOT NULL COMMENT '修改时间',
  `update_by` varchar(64)  NULL DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18)  NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21)  NOT NULL DEFAULT '-1' COMMENT '库区ID',
  PRIMARY KEY (`id`, `update_time`) USING BTREE,
  UNIQUE INDEX `unx_nf`(`nf`, `ccqy`, `ylpz`, `ylxz`) USING BTREE COMMENT '年份/承储企业/粮食品种/粮食性质组合唯一索引',
  INDEX `idx_cbgmjhwh`(`cbgmjhwh`) USING BTREE COMMENT '储备规模计划文号普通索引',
  INDEX `idx_ccqy`(`ccqy`) USING BTREE COMMENT '承储企业普通索引',
  INDEX `idx_ylpz`(`ylpz`) USING BTREE COMMENT '粮食品种代码普通索引',
  INDEX `idx_ylxz`(`ylxz`) USING BTREE COMMENT '粮食性质代码普通索引',
  INDEX `idx_region_id`(`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  INDEX `idx_region_ids`(`country_id`, `province_id`, `city_id`, `area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  INDEX `idx_enterprise`(`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  INDEX `idx_stock_house`(`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE = InnoDB COMMENT = '行政管理-储备规模表';