CREATE TABLE IF NOT EXISTS `apparitor_rotation_plan`  (
  `id` varchar(25)  NOT NULL COMMENT '主键id(轮换计划单号)',
  `lhjhdh` varchar(25)  NOT NULL COMMENT '轮换计划单号',
  `jhwh` varchar(64)  NOT NULL COMMENT '计划文号',
  `jhmc` varchar(256)  NOT NULL COMMENT '计划名称',
  `jhnd` varchar(4)  NOT NULL COMMENT '计划年度',
  `kszxrq` date NOT NULL COMMENT '开始执行日期',
  `jzzxrq` date NOT NULL COMMENT '截止执行日期',
  `jhxddw` varchar(18)  NOT NULL COMMENT '计划下达单位',
  `jhxddwmc` varchar(256)  NULL DEFAULT NULL COMMENT '计划下达单位名称',
  `jhxdsj` datetime(0) NOT NULL COMMENT '计划下达时间',
  `czbz` varchar(1)  NULL DEFAULT NULL COMMENT '操作标志',
  `zhgxsj` datetime(0) NULL DEFAULT NULL COMMENT '最后更新时间',
  `create_by` varchar(64)  NULL DEFAULT NULL COMMENT '创建人',
  `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(64)  NULL DEFAULT NULL COMMENT '修改人',
  `update_time` datetime(0) NOT NULL COMMENT '修改时间',
  `region_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10)  NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18)  NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21)  NOT NULL DEFAULT '-1' COMMENT '库区ID',
  PRIMARY KEY (`id`, `update_time`) USING BTREE,
  UNIQUE INDEX `unx_lhjhdh`(`lhjhdh`) USING BTREE COMMENT '轮换计划单号唯一索引',
  INDEX `idx_jhxddw`(`jhxddw`) USING BTREE COMMENT '计划下达单位普通索引',
  INDEX `idx_jhwh`(`jhwh`) USING BTREE COMMENT '计划文号普通索引',
  INDEX `idx_region_id`(`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  INDEX `idx_region_ids`(`country_id`, `province_id`, `city_id`, `area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  INDEX `idx_enterprise`(`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  INDEX `idx_stock_house`(`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE = InnoDB COMMENT = '行政管理-轮换计划主表';