CREATE TABLE IF NOT EXISTS `plan_reserve_scale_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `remarks` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  `region_code` varchar(20) DEFAULT NULL COMMENT '行政区划编码',
  `region_parent_code` varchar(20) DEFAULT NULL COMMENT '行政区划父级编码',
  `grain_amount` decimal(20,4) DEFAULT NULL COMMENT '粮食储备规模数量（万吨）',
  `oil_amount` decimal(20,4) DEFAULT NULL COMMENT '油储备规模数量（万吨）',
  `is_area` char(2) DEFAULT NULL COMMENT '是否有区县',
  `adjust_grain_amount` decimal(20,4) DEFAULT NULL COMMENT '调整后粮食储备规模数量（万吨）',
  `adjust_oil_amount` decimal(20,4) DEFAULT NULL COMMENT '调整后油储备规模数量（万吨）',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引',
  KEY `idx_region_parent_code` (`region_parent_code`) USING BTREE COMMENT '行政区划父级代码普通索引',
  KEY `idx_region_code` (`region_code`) USING BTREE COMMENT '行政区划代码普通索引'
) ENGINE=InnoDB AUTO_INCREMENT=584 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='储备计划管理-储备规模调整日志表';