db:
  driverClassname: com.mysql.cj.jdbc.Driver
  host: 173.18.15.28
  port: 3306
  database: gd-province-platform
  username: root
  password: Sm6Tq1Gg8@

redis:
  database: 0
  host: 173.18.15.30
  port: 6379
  password: Sm6Tq1Gg8@

minio:
  url: http://173.18.15.29:29000
  accessKey: minioadmin
  secretKey: Sm6Tq1Gg8@
  bucketName: gd-province-platform

spring:
  boot:
    admin:
      client:
        enabled: false
        url: http://173.18.15.29:8400/admin
        instance:
          service-host-type: ip
  flyway:
    enabled: false

xxl-job:
  enabled: false
  adminAddresses: http://173.18.15.29:8500/gd-job
  appname: ${spring.application.name}
  logPath: ./logs/jobhandler
  logRetentionDays: 30
  loginIdentity: 7b226964223a312c22757365726e616d65223a2261646d696e222c2270617373776f7264223a226665306264346135623233616132656365376132626631363263353130326435222c22726f6c65223a312c227065726d697373696f6e223a6e756c6c7d

# 接口文档配置
swagger:
  enabled: false

arthas:
  tunnel-server: ws://173.18.15.29:7777/ws
  telnet-port: -1
  http-port: -1

# 省平台下发市平台（库软件）地址
spt:
  host: http://173.18.15.27:80

# 广东省统一身份认证配置
gds-unified-identity:
  baseUrl: https://xtbg.gdzwfw.gov.cn
  clientId: zwrz_gdlkznh
  clientSecret: cdc7937C34EF4378wniq
  grantType: authorization_code
  responseType: code
  scope: all
  timeoutUnit: SECONDS
  callTimeout: 300
  connectTimeout: 300
  readTimeout: 300
  writeTimeout: 300