CREATE TABLE IF NOT EXISTS `plan_manage_audit` (
  `id` varchar(40) NOT NULL COMMENT '轮换计划审核Id',
  `main_code` varchar(60)  DEFAULT NULL COMMENT '单据编号',
  `plan_tenant_name` varchar(256) NOT NULL COMMENT '计划下达单位',
  `jhxddw` varchar(40) NOT NULL COMMENT '计划下达单位统一社会信用代码',
  `jhnd` varchar(4) DEFAULT NULL COMMENT '计划年度',
  `lhjhdh` varchar(25) DEFAULT NULL COMMENT '轮换计划单号',
  `jhmc` varchar(256) DEFAULT NULL COMMENT '计划名称',
  `management_style` varchar(60)  NOT NULL COMMENT '管理方式',
  `management_style_name` varchar(60)  NOT NULL COMMENT '管理方式名称',
  `jhwh` varchar(64) DEFAULT NULL COMMENT '计划文号',
  `plan_in_qty` decimal(20,4) DEFAULT NULL COMMENT '轮入数量（t）',
  `plan_out_qty` decimal(20,4) DEFAULT NULL COMMENT '轮出数量（t）',
  `lsxzdm` varchar(3) DEFAULT NULL COMMENT '粮食性质代码',
  `jhxdsj` date NOT NULL COMMENT '计划下达日期',
  `kszxrq` date NOT NULL COMMENT '计划执行日期开始',
  `jzzxrq` date NOT NULL COMMENT '计划执行日期截止',
  `bill_status` varchar(20)  DEFAULT NULL COMMENT '单据状态',
  `bill_status_name` varchar(20)  DEFAULT NULL COMMENT '单据状态名称',
  `plan_status` varchar(20)  DEFAULT NULL COMMENT '轮换状态',
  `plan_status_name` varchar(20)  DEFAULT NULL COMMENT '轮换状态名称',
  `remark` varchar(500)  DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  `main_id` varchar(20) DEFAULT NULL COMMENT '库软件轮换计划Id',
  `czbz` varchar(2) DEFAULT NULL COMMENT '操作标志',
  `zhgxsj` datetime DEFAULT NULL COMMENT '最后更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引',
	KEY `idx_main_id` (`main_id`) USING BTREE COMMENT '库软件mainId普通索引'
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC COMMENT='轮换计划审核';

CREATE TABLE IF NOT EXISTS `plan_manage_audit_dtl` (
  `id` varchar(40) NOT NULL COMMENT '轮换计划审核详情Id',
  `main_id` varchar(25) DEFAULT NULL COMMENT '轮换计划审核id',
  `plan_main_id` varchar(25) DEFAULT NULL COMMENT '库软件轮换计划审核id',
  `detail_id` varchar(25) DEFAULT NULL COMMENT '库软件轮换计划详情id',
  `lhjhdh` varchar(25) DEFAULT NULL COMMENT '轮换计划单号',
  `lhhwdm` varchar(40)  DEFAULT NULL COMMENT '轮换货位代码',
  `lspzdm` varchar(60)  DEFAULT NULL COMMENT '粮食品种代码',
  `lsdjdm` varchar(7) DEFAULT NULL COMMENT '粮食等级代码：字典food_grade',
  `lsdjdm_name` varchar(7) DEFAULT NULL COMMENT '粮食等级代码名称：字典food_grade',
  `shnd` varchar(4) DEFAULT NULL COMMENT '收货年度',
  `lhlx` varchar(6) DEFAULT NULL COMMENT '轮换类型',
  `lhlx_name` varchar(6) DEFAULT NULL COMMENT '轮换类型名称',
  `lhsl` decimal(20,3) DEFAULT NULL COMMENT '轮换数量',
  `carry_qty` decimal(20,6) DEFAULT NULL COMMENT '执行数量（t）',
  `price` decimal(20,2) DEFAULT NULL COMMENT '基准价(元/公斤)',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引',
  KEY `idx_plan_main_id` (`plan_main_id`) USING BTREE COMMENT '库软件mainId普通索引',
  KEY `detail_id` (`detail_id`) USING BTREE COMMENT '库软件detailId普通索引'
) ENGINE=InnoDB  ROW_FORMAT=DYNAMIC COMMENT='轮换计划审核详情';

delete from basis_dict where dict_type = 'apiCode' and dict_key = '1003';
delete from basis_dict where dict_type = 'apiCode' and dict_key = '1004';
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('apiCode', 0, '1003', '轮换计划信息', '', NULL, '轮换计划信息', NULL, NULL, NULL, NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('apiCode', 0, '1004', '轮换计划信息查询', '', NULL, '轮换计划信息查询', NULL, NULL, NULL, NULL, '2023-01-30 10:44:55');
delete from basis_dict where dict_type = 'plan_manage_status';
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('plan_manage_status', 1, 'audit_pass', '审核通过', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('plan_manage_status', 2, 'audit_failed', '审核不通过', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
