CREATE TABLE IF NOT EXISTS  `apparitor_culture` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '人才培养计划id',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '最后更新者',
  `update_time` datetime DEFAULT NULL COMMENT '最后更新时间',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户ID',
  `enterprise_id` bigint DEFAULT NULL COMMENT '租户ID',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `stock_house_id` varchar(21) DEFAULT '-1' COMMENT '库区ID',
  `dept_id` varchar(60) DEFAULT NULL COMMENT '部门',
  `file_name` varchar(255) DEFAULT NULL COMMENT '文件标题',
  `remark` varchar(2000) DEFAULT NULL COMMENT '文件描述',
  `approved_name` varchar(60) DEFAULT NULL COMMENT '审核人名称',
  `approved_time` datetime DEFAULT NULL COMMENT '审核时间',
  `bill_status` varchar(20) DEFAULT NULL COMMENT '状态1拟稿，2待审核，3发布',
  `file_attachment` longtext COMMENT '附件记录',
  `dwdm` varchar(18) NOT NULL COMMENT '单位代码',
  `dwmc` varchar(256) NOT NULL COMMENT '单位名称',
  PRIMARY KEY (`id`),
  KEY `idx_dwdm` (`dwdm`) USING BTREE COMMENT '单位代码普通索引',
  KEY `idx_dwmc` (`dwmc`) USING BTREE COMMENT '单位名称普通索引',
  KEY `idx_file_name` (`file_name`) USING BTREE COMMENT '文件标题普通索引',
  KEY `idx_dept_id` (`dept_id`) USING BTREE COMMENT '部门id普通索引',
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE=InnoDB  COMMENT='行政管理-人才培养计划';

CREATE TABLE IF NOT EXISTS  `apparitor_title` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '荣誉称号管理id',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '最后更新者',
  `update_time` datetime DEFAULT NULL COMMENT '最后更新时间',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户ID',
  `enterprise_id` bigint DEFAULT NULL COMMENT '租户ID',
  `czbz` char(1) NOT NULL COMMENT '操作标志',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `stock_house_id` varchar(21) DEFAULT '-1' COMMENT '库区ID',
  `dept_id` varchar(60) DEFAULT NULL COMMENT '部门',
  `title_type_id` bigint DEFAULT NULL COMMENT '称号类别id',
  `bill_status` varchar(20) DEFAULT NULL COMMENT '状态',
  `personnel_id` varchar(60) DEFAULT NULL COMMENT '人员ID',
  `dwdm` varchar(18) NOT NULL COMMENT '单位代码',
  `dwmc` varchar(256) NOT NULL COMMENT '单位名称',
  PRIMARY KEY (`id`),
  KEY `idx_dwdm` (`dwdm`) USING BTREE COMMENT '单位代码普通索引',
  KEY `idx_dwmc` (`dwmc`) USING BTREE COMMENT '单位名称普通索引',
  KEY `idx_title_type_id` (`title_type_id`) USING BTREE COMMENT '称号类别普通索引',
  KEY `idx_bill_status` (`bill_status`) USING BTREE COMMENT '状态普通索引',
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE=InnoDB COMMENT='行政管理-荣誉称号管理';

CREATE TABLE IF NOT EXISTS  `apparitor_title_type` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '称号类别管理Id',
  `type_name` varchar(50) DEFAULT NULL COMMENT '分类名称',
  `parent_id` bigint DEFAULT '0' COMMENT '父类ID',
  `all_parent_id` varchar(100) DEFAULT NULL COMMENT '所有上级id',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_leaf_node` char(1) DEFAULT '1' COMMENT '是否叶节点(1是 0否)',
  `is_enable` char(1) DEFAULT '1' COMMENT '启用状态(1正常 0停用)',
  `del_flag` char(1) DEFAULT '0' COMMENT '删除标志(0正常 1被删除)',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '最后更新者',
  `update_time` datetime DEFAULT NULL COMMENT '最后更新时间',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户ID',
  `enterprise_id` bigint DEFAULT NULL COMMENT '租户ID',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `stock_house_id` varchar(21) DEFAULT '-1' COMMENT '库区ID',
  PRIMARY KEY (`id`),
   KEY `idx_type_name` (`type_name`) USING BTREE COMMENT '分类名称普通索引',
  KEY `idx_parent_id` (`parent_id`) USING BTREE COMMENT '父类ID普通索引',
  KEY `idx_all_parent_id` (`all_parent_id`) USING BTREE COMMENT '所有上级id普通索引',
  KEY `idx_is_enable` (`is_enable`) USING BTREE COMMENT '启用状态普通索引',
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE=InnoDB COMMENT='行政管理-称号类别管理';