CREATE TABLE IF NOT EXISTS `plan_reserve_plan` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `remarks` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  `plan_code` varchar(120) DEFAULT NULL COMMENT '计划文号',
  `plan_name` varchar(120) DEFAULT NULL COMMENT '计划名称',
  `ylxz` varchar(60) DEFAULT NULL COMMENT '粮食性质',
  `amount` decimal(20,2) DEFAULT NULL COMMENT '承储总数量（吨）',
  `begin_date` date DEFAULT NULL COMMENT '计划开始日期',
  `end_date` date DEFAULT NULL COMMENT '计划结束日期',
  `jhxdsj` date DEFAULT NULL COMMENT '计划下达时间',
  `jhnd` varchar(20) DEFAULT NULL COMMENT '年份如2022',
  `jhzddw` varchar(20) DEFAULT NULL COMMENT '制定计划单位',
  `ccqy` varchar(20) DEFAULT NULL COMMENT '承储企业',
  `jhdh` varchar(60) DEFAULT NULL COMMENT '计划单号',
  `file_attachment` longtext COMMENT '附件',
  `bill_status` varchar(20) DEFAULT NULL COMMENT '状态',
  `is_change` varchar(20) DEFAULT NULL COMMENT '是否发生调整',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引',
  KEY `idx_plan_code` (`plan_code`) USING BTREE COMMENT '计划文号普通索引',
  KEY `idx_plan_name` (`plan_name`) USING BTREE COMMENT '计划名称普通索引'
) ENGINE=InnoDB  COMMENT='储备计划管理-储备规模表';

CREATE TABLE IF NOT EXISTS `plan_reserve_plan_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `main_id` bigint DEFAULT NULL COMMENT '主表ID',
  `detail_id` bigint DEFAULT NULL COMMENT '详情表id',
  `lsdjdm` varchar(40) DEFAULT NULL COMMENT '粮食等级代码',
  `remarks` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  `ylpz` varchar(60) DEFAULT NULL COMMENT '粮食品种',
  `amount` decimal(20,2) DEFAULT NULL COMMENT '承储数量（吨）',
  `remark` varchar(20) DEFAULT NULL COMMENT '承储质量要求',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE=InnoDB  COMMENT='储备计划管理-储备规模调整历史';

CREATE TABLE IF NOT EXISTS `plan_reserve_plan_dtl` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `main_id` bigint DEFAULT NULL COMMENT '主表ID',
  `lsdjdm` varchar(40) DEFAULT NULL COMMENT '粮食等级代码',
  `remarks` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `create_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `update_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  `ylpz` varchar(60) DEFAULT NULL COMMENT '粮食品种',
  `amount` decimal(20,2) DEFAULT NULL COMMENT '承储数量（吨）',
  `remark` varchar(20) DEFAULT NULL COMMENT '承储质量要求',
  `bill_status` varchar(20) DEFAULT NULL COMMENT '状态',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE=InnoDB  COMMENT='储备计划管理-储备规模详情表';