delete from basis_dict where dict_type = 'food_nature_other';
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '100', '储备粮', NULL, NULL, NULL, '储备粮', 'admin', '2022-07-28 15:31:29', '超级管理员', '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '110', '中央储备粮', NULL, NULL, NULL, '中央储备粮', 'admin', '2022-07-28 15:31:29', NULL, '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '120', '地方储备粮', NULL, NULL, NULL, '地方储备粮', 'admin', '2022-07-28 15:31:29', NULL, '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '129', '其他储备粮', NULL, NULL, NULL, '其他储备粮', 'admin', '2022-07-28 15:31:29', NULL, '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '321', '国家一次性储备', '', NULL, NULL, '国家一次性储备', NULL, '2023-03-27 18:37:14', NULL, '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '331', '国家进口周转储备', '', NULL, NULL, '国家进口周转储备', NULL, '2023-03-27 18:37:37', NULL, '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '350', '中央调节储备', NULL, NULL, NULL, '中央调节储备', 'admin', '2022-07-28 15:31:29', NULL, '2023-04-28 15:14:15');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('food_nature_other', 0, '360', '地方调节储备', NULL, NULL, NULL, '地方调节储备', 'admin', '2022-07-28 15:31:29', NULL, '2023-04-28 15:14:15');
