CREATE TABLE IF NOT EXISTS `apparitor_personnel` (
  `id` varchar(37) NOT NULL COMMENT '主键ID(单位代码-身份证号码)',
  `dwdm` varchar(18) NOT NULL COMMENT '单位代码',
  `kqdm` varchar(21) DEFAULT NULL COMMENT '库区代码',
  `dwmc` varchar(256) NOT NULL COMMENT '单位名称',
  `lsbm` varchar(256) NOT NULL COMMENT '隶属部门',
  `xzqhdm` varchar(6) NOT NULL COMMENT '行政区划代码',
  `xm` varchar(32) NOT NULL COMMENT '姓名',
  `xb` char(1) NOT NULL COMMENT '性别',
  `sfzhm` char(18) NOT NULL COMMENT '身份证号码',
  `rzrq` date NOT NULL COMMENT '入职日期',
  `gwxz` char(2) NOT NULL COMMENT '岗位性质',
  `zgzt` char(2) NOT NULL COMMENT '在岗状态',
  `lzrq` date DEFAULT NULL COMMENT '离职日期',
  `zjdh` varchar(16) DEFAULT NULL COMMENT '座机电话',
  `yddh` varchar(16) DEFAULT NULL COMMENT '移动电话',
  `dzyx` varchar(32) DEFAULT NULL COMMENT '电子邮箱',
  `mz` char(2) NOT NULL COMMENT '民族',
  `zzmm` char(2) NOT NULL COMMENT '政治面貌',
  `rylb` char(4) NOT NULL COMMENT '人员类别',
  `zy` varchar(128) DEFAULT NULL COMMENT '专业',
  `qdzgzchzyzgsj` date DEFAULT NULL COMMENT '取得最高职称或职业资格时间',
  `xl` char(1) NOT NULL COMMENT '学历',
  `zw` varchar(16) DEFAULT NULL COMMENT '职务',
  `czbz` char(1) NOT NULL COMMENT '操作标志',
  `zhgxsj` datetime NOT NULL COMMENT '最后更新时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime NOT NULL COMMENT '修改时间',
  `region_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '行政区域ID',
  `country_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '国ID',
  `province_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '省ID',
  `city_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '市ID',
  `area_id` varchar(10) NOT NULL DEFAULT '-1' COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  PRIMARY KEY (`id`,`update_time`),
  UNIQUE KEY `unx_sfzhm` (`dwdm`,`sfzhm`) USING BTREE COMMENT '单位代码/身份证号码组合唯一索引',
  KEY `idx_dwmc` (`dwmc`) USING BTREE COMMENT '单位名称普通索引',
  KEY `idx_xm` (`xm`) USING BTREE COMMENT '姓名普通索引',
  KEY `idx_sfzhm` (`sfzhm`) USING BTREE COMMENT '身份证号码普通索引',
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '国/省/市/区组合普通索引',
  KEY `idx_update_time` (`update_time`) USING BTREE COMMENT '最后更新时间普通索引',
  KEY `idx_enterprise` (`enterprise_id`) USING BTREE COMMENT '企业ID普通索引',
  KEY `idx_stock_house` (`stock_house_id`) USING BTREE COMMENT '库区ID普通索引'
) ENGINE=InnoDB COMMENT='行政管理-企业人员信息表';