CREATE TABLE IF NOT EXISTS `reserve_layout_company`  (
    `id` varchar(18)  NOT NULL COMMENT '主键ID(单位代码)',
    `dwdm` varchar(18)  NOT NULL COMMENT '单位代码',
    `dwmc` varchar(256)  NOT NULL COMMENT '单位名称',
    `dwlx` varchar(2)  NOT NULL COMMENT '单位类型',
    `zcrq` date NOT NULL COMMENT '注册日期',
    `zczb` decimal(20, 6) NULL DEFAULT NULL COMMENT '注册资本',
    `zcze` decimal(20, 6) NULL DEFAULT NULL COMMENT '资产总额',
    `fddbr` varchar(100)  NOT NULL COMMENT '法定代表人',
    `frsfzh` varchar(18)  NOT NULL COMMENT '法人身份证号',
    `frlxfs` varchar(50)  NULL DEFAULT NULL COMMENT '法人联系方式',
    `qylxr` varchar(100)  NOT NULL COMMENT '企业联系人',
    `bgdh` varchar(50)  NOT NULL COMMENT '办公电话',
    `zcdz` varchar(512)  NOT NULL COMMENT '注册地址',
    `dzyx` varchar(50)  NULL DEFAULT NULL COMMENT '电子邮箱',
    `qygfwzdz` varchar(128)  NULL DEFAULT NULL COMMENT '企业官方网站地址',
    `czhm` varchar(32)  NULL DEFAULT NULL COMMENT '传真号码',
    `yzbm` varchar(6)  NULL DEFAULT NULL COMMENT '邮政编码',
    `xzqhdm` varchar(6)  NOT NULL COMMENT '行政区划代码',
    `sjdwmc` varchar(256)  NULL DEFAULT NULL COMMENT '上级单位名称',
    `sjdwdm` varchar(18)  NULL DEFAULT NULL COMMENT '上级单位代码',
    `kqs` int(0) NOT NULL COMMENT '库区数',
    `cfs` int(0) NOT NULL COMMENT '仓房数',
    `ygs` int(0) NOT NULL COMMENT '油罐数',
    `jd` decimal(20, 6) NULL DEFAULT NULL COMMENT '经度',
    `wd` decimal(20, 6) NULL DEFAULT NULL COMMENT '纬度',
    `status` char(1)  NOT NULL DEFAULT '0' COMMENT '状态 0：保存，1：提交，2：审核',
    `create_by` varchar(50)  NULL DEFAULT NULL COMMENT '创建者',
    `create_time` datetime(0) NULL DEFAULT NULL COMMENT '创建时间',
    `update_by` varchar(50)  NULL DEFAULT NULL COMMENT '更新者',
    `update_time` datetime(0) NOT NULL COMMENT '修改时间',
    `yzyjhys` char(1)  NULL DEFAULT NULL COMMENT '有专用检化验室 1:有,0:无',
    `lycgjynl` char(1)  NULL DEFAULT NULL COMMENT '具有粮油常规检验能力 1:有,0:无',
    `lypzjynl` char(1)  NULL DEFAULT NULL COMMENT '具有粮油品质检验能力 1:有,0:无',
    `zbywwxy` char(1)  NULL DEFAULT NULL COMMENT '周边有无危险源 1:有,0:无',
    `zbywwry` char(1)  NULL DEFAULT NULL COMMENT '周边有无污染源 1:有,0:无',
    `jylypzjynl` char(1)  NULL DEFAULT NULL COMMENT '具有粮油品质检验能力 1:有,0:无',
    `lxrzw` varchar(32)  NULL DEFAULT NULL COMMENT '联系人职务',
    `cyryzs` int(0) NULL DEFAULT NULL COMMENT '从业人员总数',
    `qzlybgrs` int(0) NULL DEFAULT NULL COMMENT '其中粮油保管员人数',
    `qzlyzjyrs` int(0) NULL DEFAULT NULL COMMENT '其中粮油质检员人数',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `unx_dwdm`(`dwdm`) USING BTREE COMMENT '单位代码唯一索引',
    INDEX `idx_dwmc`(`dwmc`) USING BTREE COMMENT '单位名称普通索引',
    INDEX `idx_update_time`(`update_time`) USING BTREE COMMENT '最后更新时间普通索引'
    ) ENGINE = InnoDB  COMMENT = '储备布局企业信息表' ROW_FORMAT = Dynamic;