-- 人员管理 人员制度管理状态
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ( 'apparitor_status', 1, '1', '拟稿', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ( 'apparitor_status', 2, '2', '发布', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 案件管理-案件类型
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ( 'case_type', 1, '1', '粮食质量', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ( 'case_type', 2, '2', '企业运营', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ( 'case_type', 3, '3', '其他', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 案件管理-案件来源
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('case_source', 1, '1', '监督检查工作', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('case_source', 2, '2', '举报', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('case_source', 3, '3', '上级交办、下级报请、有关部门移送或其他方式披露的监督检查事项', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 规划建设-仓储设施建设管理-项目进展
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('xmjz_code', 1, '01', '设计', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('xmjz_code', 2, '02', '立项', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('xmjz_code', 3, '03', '招标', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('xmjz_code', 4, '04', '开工', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('xmjz_code', 5, '05', '完工', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('xmjz_code', 6, '06', '验收', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 安全仓储-制度类别管理-启用状态
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('is_enable', 1, '01', '正常', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('is_enable', 2, '02', '停用', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 安全仓储-制度类别管理-是否叶节点
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('is_leaf_node', 1, '01', '是', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('is_leaf_node', 2, '02', '否', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 安全仓储-风险智能识别-风险类型
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 1, '01', '收购', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 2, '02', '库存', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 3, '03', '销售', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 4, '04', '轮换', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 5, '05', '补贴', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 6, '06', '贷款', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 7, '07', '质量', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 8, '08', '仓储', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('risk_type', 9, '09', '其他', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');

-- 安全仓储-风险智能识别-预警类型
INSERT INTO `basis_dict`( `dict_type`, `dict_sort`, `dict_key`, `dict_value`, `dict_parent_key`, `dict_top_key`, `dict_far_type`, `remark`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('yjlx_type', 1, '01', '质量', '', NULL, NULL, '', NULL, '2022-08-24 14:24:25', NULL, '2023-01-30 10:44:55');