CREATE TABLE IF NOT EXISTS `dashboard_warehouse_capacity` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `cfdm` varchar(25)	NOT NULL COMMENT '仓房代码',
  `cflxdm` varchar(8)	NOT NULL COMMENT '仓房类型',
  `jfsyrq` date COMMENT '交付使用日期',
  `lspzdm` varchar(7) COMMENT '粮食品种代码',
  `lsxzdm` varchar(3) COMMENT '粮食性质代码',
  `sjcr` decimal(20,6) NOT NULL COMMENT '设计仓容',
  `jjsl` decimal(20,6) NOT NULL COMMENT '计价数量',
  `sl` decimal(20,6)  COMMENT '计划数量',
  `lrsl` decimal(20,6)  COMMENT '轮入数量',
  `lcsl` decimal(20,6)  COMMENT '轮出数量',
  `region_id` varchar(10) DEFAULT NULL COMMENT '行政区域ID',
  `country_id` varchar(10) DEFAULT NULL COMMENT '国ID',
  `province_id` varchar(10) DEFAULT NULL COMMENT '省ID',
  `city_id` varchar(10) DEFAULT NULL COMMENT '市ID',
  `area_id` varchar(10) DEFAULT NULL COMMENT '区ID',
  `enterprise_id` varchar(18) NOT NULL DEFAULT '-1' COMMENT '企业ID',
  `stock_house_id` varchar(21) NOT NULL DEFAULT '-1' COMMENT '库区ID',
  `create_time` datetime DEFAULT null COMMENT '统计时间',
  PRIMARY KEY (`id`),
  KEY `idx_cflxdm` (`cflxdm`) USING BTREE COMMENT '仓房类型普通索引',
  KEY `idx_stock_house_id` (`stock_house_id`) USING BTREE COMMENT '库区id普通索引',
  KEY `idx_lsxzdm` (`lsxzdm`) USING BTREE COMMENT '粮食性质代码普通索引',
  KEY `idx_region_id` (`region_id`) USING BTREE COMMENT '行政区域ID普通索引',
  KEY `idx_region_ids` (`country_id`,`province_id`,`city_id`,`area_id`) USING BTREE COMMENT '行政地区组合索引'
) ENGINE=MyISAM COMMENT='报表管理-仓库容量报表';